name:        muzak
version:     0.1.0
synopsis:    Some easy listening.
github:      doogonthehorizon/muzak
license:     GPL3
author:      Fernando Freire
maintainer:  dogonthehorizon@gmail.com
copyright:   2019 Fernando Freire
category:    Music
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - tidal

executables:
  muzak:
    source-dirs:      src
    main:             Main.hs
